apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: kifume
spec:
  version: 8.7.0
  count: 1
  elasticsearchRef:
    name: quickstart
    namespace: kifume
  http:
    service:
      spec:
        type: LoadBalancer