apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jupyter-pvc
  name: jupyter-pvc
  namespace: kifume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath