apiVersion: v1
kind: Service
metadata:
  name: jupyter2
  namespace: kifume
  labels:
    app: jupyter2
spec:
  ports:
  - name: http
    port: 8888
  selector:
    app: jupyter2
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: jupyter2
  namespace: kifume
  labels:
    app: jupyter2
spec:
  containers:
    - name: jupyter2
      image: jupyter/minimal-notebook
      ports:
      - containerPort: 8888
        protocol: TCP
        name: http
      volumeMounts:
      - mountPath: /jupyter
        name: jupyter2

  volumes:
  - name: jupyter2
    persistentVolumeClaim:
      claimName: jupyter-pvc