apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kifume
  name: onedrive-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/mkisono/OneDrive
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: onedrive-conf-pvc
  name: onedrive-conf-pvc
  namespace: kifume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: onedrive-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: onedrive-data-pvc
  name: onedrive-data-pvc
  namespace: kifume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: onedrive-hostpath
