apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: onedrive-conf-pvc
  name: onedrive-conf-pvc
  namespace: kifume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: onedrive-data-pvc
  name: onedrive-data-pvc
  namespace: kifume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath